<?php
/**
 * Copyright © Deki. All rights reserved.
 * See COPYING.txt for license details.
 */

?>
<script type="text/x-magento-init">
    {
        "#city": {
            "city-autocomplete": {
                "enablePostcode": <?=
                    /* @noEscape */ $block->getConfig('customeraddress/general/enable_postcode') ? 'true' : 'false'
                ?>,
                "minLength": <?=
                    /* @noEscape */ $block->getConfig('customeraddress/general/minimum_search_length')
                ?>,
                "isForceCityEnabled": <?=
                    /* @noEscape */ $block->getConfig('customeraddress/general/force_select_city')
                ?>
            }
        }

    }
</script>
