<?php
/**
 * Copyright © Deki, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var $block \Deki\CustomerAddress\Block\Adminhtml\System\Config\Info */
/** @var \Magento\Framework\View\Helper\SecureHtmlRenderer $secureRenderer */
?>
<div>
    <p>
        <strong><?= __('Installed Version : ').$block->getVersion() ?></strong>
    </p>
    <p>
        <strong><?= __('Latest Version : ').$block->getLatestVersion() ?></strong>
    </p>
    <p>
        <?= __('Github Link : ')?>
        <a href="<?= $block->getGithubUrl() ?>" target="_blank">
            <?= __('Click Here') ?>
        </a>
    </p>
    <p>
        <?= __('Docs Link : ')?>
        <a href="<?= $block->getDocsUrl() ?>" target="_blank">
            <?= __('Click Here') ?>
        </a>
    </p>
</div>