<?php
/**
 * Copyright © Deki, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var $block \Deki\CustomerAddress\Block\Adminhtml\Customer\Address\Edit\ConfigJs */
/** @var \Magento\Framework\View\Helper\SecureHtmlRenderer $secureRenderer */
?>

<?php $serializedConfig = /* @noEscape */ $block->getSerializedConfig();
$scriptString = <<<script
    window.customerAddressConfig = {$serializedConfig};
script;
?>
<?= /* @noEscape */ $secureRenderer->renderTag('script', [], $scriptString, false) ?>

